[914053] Replace stack traces with appropriate error messages and info
CAFapi/caf-logging pull request #28
Opened 2024-05-20 09:25 UTC by simranjeetc

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=914053

With this change we can limit the stacktraces by providing the below properties in the includedLogback.xml

Example -
```xml
<property name="packages" value="com.github;org.github"/>
<property name="maxStackTraceLines" value="4"/>
```
Both the options packages & maxStackTraceLines are optional and mutually exclusive

packages - With this stacktrace filters the entries to allow only the provided packages. Multiple packages can be separated by semicolon
maxStackTraceLines - Limits the maximum number of stacktrace entries that go into the log

2024-05-20 09:26 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://sou-jenkins2.swinfra.net/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=CAFapi&REPO_NAME=caf-logging&BRANCH_NAME=914053) to go ahead and create the build...

2024-05-20 09:31 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://sou-jenkins2.swinfra.net/job/CAFapi/job/CAFapi~caf-logging~914053~CI

2024-05-22 22:24 UTC, dermot-hardy requested changes

2024-05-22 22:24 UTC, dermot-hardy commented on caf-logging-logback/src/test/java/com/github/cafapi/logging/logback/LogInjectionTests.java
> +        Assert.assertThat(log, not(containsString("jdk.internal")));
Why test for `jdk.internal` being not present?  So far as I can see this is the exception that was logged before and that wasn't there to begin with:

    java.lang.ArithmeticException: / by zero
	    at com.github.cafapi.logging.logback.LogInjectionTests.testLogExceptionMessage(LogInjectionTests.java:90)
	    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:498)
	    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	    at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	    at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

2024-05-22 22:24 UTC, dermot-hardy commented on caf-logging-logback-converters/pom.xml
> +        </dependency>
I don't see you needing either of these.

```suggestion
```

2024-05-22 22:24 UTC, dermot-hardy commented on caf-logging-logback/pom.xml
> +        </dependency>
These are runtime dependencies.  I don't understand why you're declaring them test-scope.  These should just be removed.

```suggestion
```

2024-05-22 22:24 UTC, dermot-hardy commented on caf-logging-logback-converters/src/main/java/com/github/cafapi/logging/logback/converters/MaybeJsonMessageConverter.java
> +    public static final String HYPHEN = "-";
```suggestion
    private static final String HYPHEN = "-";
```

2024-05-22 22:24 UTC, dermot-hardy commented on caf-logging-logback-converters/src/main/java/com/github/cafapi/logging/logback/converters/MaybeJsonMessageConverter.java
> +    private String getPackages(final List<String> optionList)
Methods that can be `static` usually should be:

```suggestion
    private static String getPackages(final List<String> optionList)
```

2024-05-22 22:24 UTC, dermot-hardy commented on caf-logging-logback-converters/src/main/java/com/github/cafapi/logging/logback/converters/MaybeJsonMessageConverter.java
> +    private String getStacktraceLineLimit(final List<String> optionList)
- `static`
- Shouldn't this method be named `getMaxStackTraceLines()` given how you've named the property?
- Formatting: Put a blank line to separate from the previous method

2024-05-22 22:24 UTC, dermot-hardy commented on caf-logging-logback-converters/src/main/java/com/github/cafapi/logging/logback/converters/CustomThrowableProxyConverter.java
> +    private int maxStackTraceSize;
These should both be `final`.

2024-05-22 22:24 UTC, dermot-hardy commented on caf-logging-logback-converters/src/main/java/com/github/cafapi/logging/logback/converters/CustomThrowableProxyConverter.java
> +public class CustomThrowableProxyConverter extends RootCauseFirstThrowableProxyConverter {
- Classes should be `final` unless you're intentionally leaving open the possibility of using them as base classes.
- They shouldn't be `public` unless they need to be.

```suggestion
final CustomThrowableProxyConverter extends RootCauseFirstThrowableProxyConverter {
```

2024-05-22 22:24 UTC, dermot-hardy commented on caf-logging-logback-converters/src/main/java/com/github/cafapi/logging/logback/converters/CustomThrowableProxyConverter.java
> +        }
If you made sure that `filteredPackages` was set to `Collections.emptyList()` in the constructor when no packages were specified then you could get rid of this check.

2024-05-22 22:24 UTC, dermot-hardy commented on caf-logging-logback-converters/src/main/java/com/github/cafapi/logging/logback/converters/CustomThrowableProxyConverter.java
> +        }
Create a `private static int getMaxStackTraceSize(final String maxLines) {...}` function for this logic.

2024-05-22 22:24 UTC, dermot-hardy commented on caf-logging-logback-converters/src/test/java/com/github/cafapi/logging/logback/converters/TestableCustomThrowableProxyConverter.java
> +    public String throwableProxyToStringPublic(final ch.qos.logback.classic.spi.IThrowableProxy tp) {
Why not have an `import` for this type?

2024-05-24 08:02 UTC, simranjeetc commented on caf-logging-logback-converters/src/main/java/com/github/cafapi/logging/logback/converters/CustomThrowableProxyConverter.java
> +public class CustomThrowableProxyConverter extends RootCauseFirstThrowableProxyConverter {
Couldn't accommodate this comment as I am extending `CustomThrowableProxyConverter` for the purpose of tests.

I have addressed all other comments in this PR.

2024-05-24 22:36 UTC, dermot-hardy approved these changes
It is unfortunate that we have this new functionality just for Logback and not for Log4J2, given that they were previously aligned, however we don't use Log4J2 much so we can just add it in a separate ticket if/when we ever need it.

2024-05-30 06:05 UTC, merged